Repository redis/go-redis, pull requests merged in 2023-10, with the labels that each got.

#2769 Json support
  commands.go
  json.go
  json_test.go
Labels: feature

#2737 Add BitMapCmdable to Cmdable.
  commands.go
Labels: bug

#2749 Creating CODEOWNERS for documentation
  .github/CODEOWNERS
Labels: maintenance

#2759 Linking to Redis learning resources
  README.md
Labels: maintenance

#2761 update PubSub.Channel documentation
  pubsub.go
Labels: maintenance

#2757 fix missing fields in different Options
  options.go
  osscluster.go
  ring.go
  sentinel.go
  universal.go
Labels: maintenance

#2726 Option types must propagage missing fields
  options.go
  ring.go
  sentinel.go
  universal.go
Labels: maintenance

#2658 fix: free turn of connection pool when leave with error
  internal/pool/pool.go
Labels: bug

#2763 BUG: BFReserveArgs - error_rate & capacity
  probabilistic.go
Labels: bug

#2674 Handle wrapped errors in scripter.Run
  error.go
  redis_test.go
Labels: bug

#2753 feat: support write the types of pointer of simple data types (#2745)
  internal/proto/writer.go
  internal/proto/writer_test.go
  internal/util/type.go
Labels: feature
