Repository redis/go-redis, pull requests merged in 2023-01, with the labels that each got.

#2367 fix: Implement `redis.Hook` (v9) for `rediscensus.TracingHook`
  extra/rediscensus/rediscensus.go
Labels: bug, v9

#2375 fix(conn): releaseConn should be executed correctly
  cluster.go
  redis.go
Labels: bug

#2371 Reduce (chain) of test dependencies
  cluster_test.go
  command_test.go
  commands_test.go
  example/del-keys-without-ttl/go.sum
  example/hll/go.sum
  example/lua-scripting/go.sum
  example/otel/go.sum
  example/redis-bloom/go.sum
  example/scan-struct/go.sum
  extra/rediscensus/go.sum
  extra/rediscmd/go.mod
  extra/rediscmd/go.sum
  extra/rediscmd/rediscmd_test.go
  extra/redisotel/go.sum
  extra/redisprometheus/go.sum
  go.mod
  go.sum
  internal/customvet/go.sum
  internal/hashtag/hashtag_test.go
  internal/hscan/hscan_test.go
  internal/internal_test.go
  internal/pool/conn_check_test.go
  internal/pool/main_test.go
  internal/pool/pool_test.go
  internal/proto/proto_test.go
  internal/proto/scan_test.go
  internal/proto/writer_test.go
  internal_test.go
  iterator_test.go
  main_test.go
  pipeline_test.go
  pool_test.go
  pubsub_test.go
  race_test.go
  redis_test.go
  ring_test.go
  sentinel_test.go
  tx_test.go
  universal_test.go
Labels: maintenance

#2368 Adding the release drafter, for release note generation
  .github/release-drafter-config.yml
  .github/workflows/commitlint.yml
  .github/workflows/release-drafter.yml
Labels: maintenance
