Repository redis/go-redis, pull requests merged in 2023-02, with the labels that each got.

#2411 test: remove deep search
  Makefile
Labels: maintenance

#2412 chore: release v9.0.2 (release.sh)
  .github/workflows/release.yml
  CHANGELOG.md
  example/del-keys-without-ttl/go.mod
  example/hll/go.mod
  example/lua-scripting/go.mod
  example/otel/go.mod
  example/redis-bloom/go.mod
  example/scan-struct/go.mod
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  package.json
  version.go
Labels: maintenance

#2425 docs: Update redisotel example for v9
  extra/redisotel/README.md
Labels: maintenance

#2413 feat(scan): scan time.Time sets the default decoding
  commands_test.go
  internal/hscan/hscan_test.go
  internal/hscan/structmap.go
Labels: feature

#2441 fix: limit the number of connections created
  internal/pool/pool.go
  internal/pool/pool_test.go
Labels: bug

#2450 redis 7.0.8 in tests
  Makefile
Labels: maintenance
