Repository redis/go-redis, pull requests merged in 2023-09, with the labels that each got.

#2699 Skip flaky tests
  redis_gears_test.go
  sentinel_test.go
  universal_test.go
Labels: maintenance

#2688 Add Redis Timeseries support
  .github/wordlist.txt
  command.go
  commands.go
  redis_timeseries.go
  redis_timeseries_test.go
Labels: feature

#2693 Updating redis binary for makefile to 7.2.1
  Makefile
Labels: maintenance

#2700 Adding stale issues workflow
  .github/workflows/stale-issues.yml
Labels: maintenance

#2708 Identify client on connect
  bench_decode_test.go
  cluster.go
  commands.go
  commands_test.go
  options.go
  redis.go
Labels: feature

#2701 Changing the suffix for probablistic commands acceptings arguments to WithArgs from Args
  probabilistic.go
  probabilistic_test.go
Labels: breakingchange

#2697 Adding Go 1.21.x for CI coverage
  .github/workflows/build.yml
  .github/workflows/doctests.yaml
Labels: maintenance

#2718 Adding CONTRIBUTING guidelines
  CONTRIBUTING.md
  README.md
Labels: maintenance

#2629 Added the support for WAITAOF which is a new command in redis ver7.2.0
  commands.go
  commands_test.go
Labels: feature

#2695 change interfaces probabilistic and redis gears from private to public
  commands.go
  probabilistic.go
  redis_gears.go
Labels: maintenance

#2716 Making command structs digestable
  .gitignore
  Makefile
  acl_commands.go
  bitmap_commands.go
  cluster_commands.go
  commands.go
  gears_commands.go
  gears_commands_test.go
  generic_commands.go
  geo_commands.go
  hash_commands.go
  hyperloglog_commands.go
  list_commands.go
  osscluster.go
  osscluster_commands.go
  osscluster_test.go
  pubsub_commands.go
  scripting_commands.go
  set_commands.go
  sortedset_commands.go
  stream_commands.go
  string_commands.go
  timeseries_commands.go
  timeseries_commands_test.go
Labels: maintenance

#2735 Bump version to 9.2.1
  example/del-keys-without-ttl/go.mod
  example/hll/go.mod
  example/lua-scripting/go.mod
  example/otel/go.mod
  example/redis-bloom/go.mod
  example/scan-struct/go.mod
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  package.json
  version.go
Labels: maintenance, skip-changelog
