Repository redis/go-redis, pull requests merged in 2024-02, with the labels that each got.

#2885 fix ConnPool race in newConn
  internal/pool/pool.go
Labels: maintenance

#2887 Add support for specifying bitcount unit as byte or bit, byte default
  bitmap_commands.go
  bitmap_commands_test.go
Labels: maintenance

#2863 Remove unnecessary Node project definition file
  package.json
Labels: maintenance

#2880 Speed up connections by sending SetInfo via a pipeline
  commands_test.go
  redis.go
  sentinel_test.go
Labels: feature

#2913 docs: README update to highlight how to disable sending client identification
  .github/wordlist.txt
  README.md
Labels: maintenance

#2915 bug: Fix SETINFO ensuring it is set-and-forget
  commands.go
  commands_test.go
  internal/util.go
  redis.go
  sentinel.go
Labels: bug

#2917 Bump go-redis version to 9.5.1
  example/del-keys-without-ttl/go.mod
  example/hll/go.mod
  example/lua-scripting/go.mod
  example/otel/go.mod
  example/redis-bloom/go.mod
  example/scan-struct/go.mod
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  version.go
Labels: maintenance
