Repository redis/go-redis, pull requests merged in 2025-05, with the labels that each got.

#2930 feat: add more stats for otel
  extra/redisotel/metrics.go
Labels: feature, redisotel

#2804 feat: add connection waiting statistics
  internal/pool/pool.go
  internal/pool/pool_test.go
Labels: feature

#3371 utils: export ParseFloat and MustParseFloat wrapping internal utils
  helper/helper.go
  internal/util/convert.go
  internal/util/convert_test.go
  search_test.go
Labels: feature, maintenance

#3362 feat: add ParseFailoverURL
  example_test.go
  sentinel.go
  sentinel_test.go
Labels: feature

#3377 test(util): add unit tests for Atoi, ParseInt, ParseUint, and ParseFloat
  internal/util/strconv_test.go
Labels: maintenance

#3369 xinfo-groups: support nil lag in XINFO GROUPS
  command.go
  commands_test.go
Labels: bug

#3370 Fix: Prevent routing reads to Redis slave nodes in loading state
  osscluster.go
Labels: bug, needs-tests

#3320 feat: Introducing StreamingCredentialsProvider for token based authentication
  .github/wordlist.txt
  .gitignore
  README.md
  auth/auth.go
  auth/auth_test.go
  auth/reauth_credentials_listener.go
  command_recorder_test.go
  doctests/lpush_lrange_test.go
  example_instrumentation_test.go
  internal/pool/conn.go
  internal_test.go
  options.go
  osscluster.go
  osscluster_test.go
  probabilistic_test.go
  redis.go
  redis_test.go
  ring_test.go
  sentinel.go
  tx.go
Labels: feature

#3388 feat(ring): add GetShardClients and GetShardClientForKey methods to Ring for shard access
  ring.go
  ring_test.go
Labels: feature
