Repository redis/go-redis, pull requests merged in 2025-02, with the labels that each got.

#3258 feat(tests): validate that ConfigSet and ConfigGet work with Modules
  .gitignore
  command.go
  commands_test.go
  main_test.go
  search_commands.go
  search_test.go
Labels: bug

#3240 DOC-4734 added geo indexing examples
  doctests/geo_index_test.go
Labels: docs-review

#3260 DOC-4799 fixed capped list example
  doctests/list_tutorial_test.go
Labels: docs-review

#3257 DOC-4332 added geo query examples
  doctests/query_geo_test.go
Labels: docs-review

#3251 DOC-4300 added exact match examples
  doctests/query_em_test.go
Labels: docs-review

#3263 fix(aggregate, search): ft.aggregate bugfixes
  search_commands.go
  search_test.go
Labels: bug, feature

#3266 fix: add unstableresp3 to cluster client
  options.go
  osscluster.go
  universal.go
  universal_test.go
Labels: bug, feature

#3259 DOC-4335 added aggregate query examples
  doctests/query_agg_test.go
Labels: docs-review

#3269 test: add test for `INFO` in RCE 8
  commands_test.go
Labels: CE 8.0

#3275 fix(search): if ft.aggregate use limit when limitoffset is zero
  search_commands.go
  search_test.go
Labels: bug

#3252 DOC-4329 added range query examples
  doctests/query_range_test.go
Labels: docs-review

#3271 fix: nil pointer dereferencing in writeArg
  example/hset-struct/README.md
  example/hset-struct/go.mod
  example/hset-struct/go.sum
  example/hset-struct/main.go
  example/scan-struct/main.go
  internal/proto/writer.go
  internal/proto/writer_test.go
Labels: bug

#2931 fix: race slice for list function of ring client
  ring.go
Labels: bug

#3255 feat: support Elasticache cluster mode by setting IsClusterMode in config
  universal.go
  universal_test.go
Labels: feature
