Repository redis/go-redis, pull requests merged in 2025-03, with the labels that each got.

#2843 feat: add hstrlen command for hash
  commands_test.go
  hash_commands.go
Labels: Stale

#3190 fix: Fixed issue with context cancelled error leading to connection spikes on Primary instances
  error.go
  osscluster.go
  osscluster_test.go
Labels: bug

#3213 Enable dialect 2 on default
  README.md
  search_commands.go
  search_test.go
Labels: breakingchange

#3298 fix: connection pool timeout, increase retries
  error.go
  error_test.go
  export_test.go
Labels: bug

#3242 DOC-4494 SADD and SMEMBERS command examples
  doctests/cmds_set_test.go
Labels: docs-review

#3234 DOC-4464 examples for llen, lpop, lpush, lrange, rpop, and rpush
  doctests/cmds_list_test.go
Labels: docs-review
