Repository redis/go-redis, pull requests merged in 2025-08, with the labels that each got.

#3449 Add VAMANA vector type to RediSearch
  search_commands.go
  search_test.go
Labels: feature

#3453 add configurable buffer sizes for Redis connections
  .github/wordlist.txt
  README.md
  internal/pool/buffer_size_test.go
  internal/pool/conn.go
  internal/pool/pool.go
  internal/proto/reader.go
  options.go
  osscluster.go
  ring.go
Labels: feature

#3443 DOC-5472 time series doc examples
  doctests/timeseries_tut_test.go
Labels: maintenance, docs-review

#3436 Add Query Builder for RediSearch commands
  search_builders.go
  search_builders_test.go
Labels: feature

#3460 chore(release): 9.12.0-beta.1
  CHANGELOG.md
  RELEASE-NOTES.md
  example/del-keys-without-ttl/go.mod
  example/hll/go.mod
  example/hset-struct/go.mod
  example/lua-scripting/go.mod
  example/otel/go.mod
  example/redis-bloom/go.mod
  example/scan-struct/go.mod
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  version.go
Labels: maintenance

#3446 improve code readability
  osscluster.go
  redis.go
  sentinel.go
Labels: maintenance

#3463 Merges stale issues jobs into one job with two steps
  .github/workflows/stale-issues.yml
Labels: maintenance

#3464 chore(release): 9.12.0 / redis 8.2
  .github/actions/run-tests/action.yml
  .github/workflows/build.yml
  RELEASE-NOTES.md
  example/del-keys-without-ttl/go.mod
  example/hll/go.mod
  example/hset-struct/go.mod
  example/lua-scripting/go.mod
  example/otel/go.mod
  example/redis-bloom/go.mod
  example/scan-struct/go.mod
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  version.go
Labels: maintenance

#3466 chore: update & fix otel example
  example/otel/README.md
  example/otel/client.go
  example/otel/config/otel-collector.yaml
  example/otel/docker-compose.yml
  example/otel/image/metrics.png
  example/otel/image/redis-trace.png
  example/otel/uptrace.yml
Labels: maintenance, redisotel

#3468 fix(options): Add buffer sizes to failover. Update README
  .github/wordlist.txt
  README.md
  internal/pool/buffer_size_test.go
  internal/proto/reader.go
  options.go
  osscluster.go
  ring.go
  sentinel.go
Labels: bug, maintenance

#3472 Clean failing timeout implementation
  options.go
  osscluster.go
  osscluster_test.go
  sentinel.go
  universal.go
Labels: feature

#3471 Removes dry run for stale issues policy
  .github/workflows/stale-issues.yml
Labels: maintenance

#3470 Ensure that JSON.GET returns Nil response
  json.go
  json_test.go
Labels: bug
