Repository redis/go-redis, pull requests merged in 2025-04, with the labels that each got.

#3345 DOC-5102 added CountOnly search example for docs
  doctests/home_json_example_test.go
Labels: docs-review

#3357 DOC-5111 added hash search examples
  doctests/home_json_example_test.go
Labels: docs-review

#3355 update HExpire command documentation
  hash_commands.go
Labels: docs-review

#3273 feat: func isEmptyValue support time.Time
  commands.go
  commands_test.go
Labels: feature

#3354 migrate golangci-lint config to v2 format
  .github/workflows/golangci-lint.yml
  .golangci.yml
  command.go
  extra/rediscensus/go.mod
  extra/rediscmd/go.mod
  extra/redisotel/go.mod
  extra/redisprometheus/go.mod
  options.go
  osscluster.go
  ring.go
  sentinel_test.go
  universal.go
Labels: dependencies, maintenance

#3363 feat(options): panic when options are nil
  osscluster.go
  redis.go
  redis_test.go
  ring.go
  sentinel.go
  universal.go
Labels: feature
