Repository redis/go-redis, pull requests merged in 2025-09, with the labels that each got.

#3495 Update the introduction to running tests in README.md
  README.md
Labels: maintenance

#3085 Do not assume that all non-IP hosts are loopbacks
  internal_test.go
  osscluster.go
Labels: bug

#3499 fix(otel): register wait metrics
  extra/redisotel/metrics.go
Labels: feature, maintenance

#3510 Added batch process method to the pipeline
  pipeline.go
  pipeline_test.go
Labels: feature

#3509 fix: SetErr on Cmd if the command cannot be queued correctly in multi/exec
  osscluster.go
  redis.go
Labels: bug

#3513 chore(release): Update the rest of the versions
  example/del-keys-without-ttl/go.mod
  example/otel/go.mod
  extra/rediscensus/go.mod
  extra/redisotel/go.mod
  scripts/tag.sh
Labels: maintenance

#3523 Update hash_commands.go
  hash_commands.go
Labels: maintenance

#3525 fix: pipeline repeatedly sets the error
  pipeline_test.go
  redis.go
Labels: bug
