Repository redis/go-redis, pull requests merged in 2025-06, with the labels that each got.

#3393 Add the missing NewFloatSliceResult for testing
  result.go
Labels: maintenance

#3375 feat: support vectorset
  command.go
  commands.go
  unit_test.go
  vectorset_commands.go
  vectorset_commands_integration_test.go
  vectorset_commands_test.go
Labels: feature

#3394 DOC-5078 vector set examples
  .github/workflows/doctests.yaml
  Makefile
  doctests/Makefile
  doctests/main_test.go
  doctests/vec_set_test.go
Labels: docs-review

#3396 fix: check if the shard exists to avoid returning nil
  ring.go
Labels: bug, redis-ring

#3407 chore(ci): update CI redis builds
  .github/actions/run-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/doctests.yaml
Labels: maintenance

#3408 [CAE-1028] fix(txpipeline): should return error on multi/exec on multiple slots
  error.go
  osscluster.go
  osscluster_test.go
Labels: bug

#3415 feat(redisotel): add WithCallerEnabled option
  extra/redisotel/config.go
  extra/redisotel/tracing.go
  extra/redisotel/tracing_test.go
Labels: feature
